development: &default
  adapter: postgresql
  encoding: utf8
  database: philly-open-health_development
  pool: 5
  username: 
  password:

test: &test
  <<: *default
  database: philly-open-health_test
cucumber:
  <<: *test